# Generated by Django 5.2.8 on 2025-11-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experience_points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='player_level',
        ),
    ]
