# Generated by Django 5.2.8 on 2025-11-20 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HTML', 'HTML'), ('PYTHON', 'Python'), ('DJANGO', 'Django'), ('JS', 'JavaScript'), ('CSS', 'CSS'), ('RANDOM', 'Random'), ('CUSTOM', 'Custom')], max_length=20, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap icon class, e.g., bi-code-slash', max_length=50, verbose_name='icon class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'quiz_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier, e.g., FIRST_WIN, STREAK_10', max_length=50, unique=True, verbose_name='trophy code')),
                ('requirement_type', models.CharField(choices=[('LEVEL', 'Player Level'), ('CATEGORY_MASTER', 'Category Mastery')], default='LEVEL', max_length=30, verbose_name='requirement type')),
                ('name', models.CharField(max_length=100, verbose_name='trophy name')),
                ('description', models.TextField(help_text='How to unlock this trophy', verbose_name='description')),
            ],
            options={
                'verbose_name': 'trophy',
                'verbose_name_plural': 'trophies',
                'db_table': 'quiz_trophy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20, verbose_name='difficulty level')),
                ('question_text', models.JSONField(default=dict, help_text='Question text in multiple languages: {"en": "...", "zh": "..."}', verbose_name='question text')),
                ('code_snippet', models.TextField(blank=True, help_text='Optional code snippet to show with the question', verbose_name='code snippet')),
                ('answer', models.CharField(help_text='The correct answer (case-insensitive)', max_length=100, verbose_name='correct answer')),
                ('hint_text', models.JSONField(blank=True, default=dict, help_text='Hint text in multiple languages: {"en": "...", "zh": "..."}', verbose_name='hint')),
                ('explanation', models.JSONField(blank=True, default=dict, help_text='Explanation in multiple languages: {"en": "...", "zh": "..."}', verbose_name='explanation')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'db_table': 'quiz_question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('end_at', models.DateTimeField(help_text='Timer deadline (when the session expires)', verbose_name='end at')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When user submitted their final answer', null=True, verbose_name='completed at')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='quiz.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'game session',
                'verbose_name_plural': 'game sessions',
                'db_table': 'quiz_game_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_level', models.PositiveIntegerField(default=1, help_text='Game progression level', verbose_name='player level')),
                ('experience_points', models.PositiveIntegerField(default=0, verbose_name='experience points')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_stats', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user statistics',
                'verbose_name_plural': 'user statistics',
                'db_table': 'quiz_user_statistics',
            },
        ),
        migrations.CreateModel(
            name='UserTrophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='unlocked at')),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trophies', to='quiz.trophy', verbose_name='trophy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user trophy',
                'verbose_name_plural': 'user trophies',
                'db_table': 'quiz_user_trophy',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='attempt number')),
                ('user_answer', models.CharField(help_text='What the user submitted', max_length=100, verbose_name='user answer')),
                ('is_correct', models.BooleanField(help_text='Whether the answer was correct', verbose_name='is correct')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='attempted at')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.gamesession', verbose_name='game session')),
            ],
            options={
                'verbose_name': 'attempt',
                'verbose_name_plural': 'attempts',
                'db_table': 'quiz_attempt',
                'ordering': ['attempt_number'],
                'indexes': [models.Index(fields=['game_session', 'attempt_number'], name='quiz_attemp_game_se_258d94_idx')],
                'unique_together': {('game_session', 'attempt_number')},
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'difficulty', 'is_active'], name='quiz_questi_categor_518e98_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='quiz_questi_created_1c91cd_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', '-started_at'], name='quiz_game_s_user_id_e298dd_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['end_at'], name='quiz_game_s_end_at_888152_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrophy',
            index=models.Index(fields=['user', '-unlocked_at'], name='quiz_user_t_user_id_c2b466_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertrophy',
            unique_together={('user', 'trophy')},
        ),
    ]
