# Generated by Django 5.2.8 on 2025-11-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='prism_language',
            field=models.CharField(blank=True, help_text='Prism.js language identifier for code highlighting, e.g., html, python, javascript', max_length=20, verbose_name='prism language'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text='FontAwesome icon class, e.g., fa-brands fa-html5, fa-brands fa-python', max_length=50, verbose_name='icon class'),
        ),
    ]
