# Generated by Django 5.2.8 on 2025-11-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_category_prism_language_alter_category_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='prism_language',
        ),
        migrations.AddField(
            model_name='question',
            name='prism_language',
            field=models.CharField(blank=True, help_text='Prism.js language for code highlighting: html, python, javascript, css, etc.', max_length=20, verbose_name='prism language'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.JSONField(blank=True, default=dict, help_text='Category description in multiple languages: {"en": "...", "zh": "..."}', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='description',
            field=models.JSONField(help_text='Bilingual description: {"en": "English", "zh": "中文"}. How to unlock this trophy', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='name',
            field=models.JSONField(help_text='Bilingual trophy name: {"en": "English", "zh": "中文"}', verbose_name='trophy name'),
        ),
    ]
